baseURL: 'http://lars.engineer/'
languageCode: 'en-us'
title: "Lars's corner"
theme: "papermod"

markup:
  goldmark:
    renderer:
      unsafe: true

params:
    # favicon: “/img/favicon.ico”
    ShowBreadCrumbs: true

    # ShowShareButtons: true 

    # ShowReadingTime: true

    # ShowPostNavLinks: true

    homeInfoParams:
        Title: "Hi there &#128075; I'm Lars"
        Content: |
            I am an AI & web3 enthousiast, currently building <a href="https://almanak.co">Almanak</a>.

            <div style="height: 23px"></div>

            If you wish to receive notifications of new content that I write, please subscribe below.
            
            <!-- Begin Mailchimp Signup Form -->
            <link href="//cdn-images.mailchimp.com/embedcode/classic-10_7_dtp.css" rel="stylesheet" type="text/css">
            <style type="text/css">
                #mc_embed_signup{clear:left; font:14px; width:350px;}
                #mc_embed_signup div.response {margin: 1em 0; font-weight: bold; float: left; top: -1.5em; z-index: 1; width: 80%;}
                #mc_embed_signup div#mce-responses {float: left; top: -1.4em; padding: 0em 0em 0em 0em; overflow: hidden; width: 90%; margin: 0 0%; clear: both;}
                #mc_embed_signup div.response {margin: 0em 0; font-weight: bold; float: left; top: -1.5em; z-index: 1; width: 80%;}
                #mc_embed_signup div.response {padding: 0em 0.5em 0.5em 0;}
            </style>
            <div id="mc_embed_signup" style="padding: 10px 0 10px 0%;">
            <form action="https://engineer.us18.list-manage.com/subscribe/post?u=c2a8f93528d97234230727d1c&amp;id=9d3bdb1154" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate style="padding: 10px 0 10px 0%;">
                <div id="mc_embed_signup_scroll">
                
            <div class="mc-field-group">
                <label for="mce-EMAIL">Email Address
            </label>
                <input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL" style="color: var(--primary);">
            </div>
                <div id="mce-responses" class="clear foot">
                    <div class="response" id="mce-error-response" style="display:none"></div>
                    <div class="response" id="mce-success-response" style="display:none"></div>
                </div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
                <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_c2a8f93528d97234230727d1c_9d3bdb1154" tabindex="-1" value=""></div>
                    <div class="optionalParent">
                        <div class="clear foot">
                            <input type="submit" value="Subscribe" name="subscribe" class="button" style="background-color: #C9CEBD; color: #1D1E20">
                        </div>
                    </div>
                </div>
            </form>
            </div>
            <script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';fnames[2]='LNAME';ftypes[2]='text';fnames[3]='ADDRESS';ftypes[3]='address';fnames[4]='PHONE';ftypes[4]='phone';fnames[5]='BIRTHDAY';ftypes[5]='birthday';}(jQuery));var $mcj = jQuery.noConflict(true);</script>
            <!--End mc_embed_signup-->

    socialIcons: # optional
        -   name: "twitter"
            url: "https://twitter.com/0xLars_"
        -   name: "github"
            url: "https://github.com/lsuanet"
        -   name: "telegram"
            url: "https://t.me/lars0x"
        -   name: "linkedin"
            url: "https://www.linkedin.com/in/larssuanet/"

languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series
        menu:
            main:
                - name: Search
                  url: /search
                  weight: 10
                - name: Garden
                  url: garden/
                  weight: 11

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary